/**
 * Berg/Trino-flavored autocomplete constants for the SQL editor.
 *
 * The pre-Berg lists were the full ClickHouse function catalogue (~1200
 * names), which on Athena would suggest dozens of functions that don't
 * exist server-side (`seriesDecomposeSTL`, `serverTimezone`, the entire
 * `array*Stable` family, etc.). We replace them with a curated subset
 * of Trino built-ins that are also supported by Athena's engine — the
 * common arithmetic / string / date / json / window helpers users hit
 * when filtering Iceberg tables. It is intentionally short: a missing
 * suggestion is better than a wrong one.
 *
 * Reference:
 *   https://trino.io/docs/current/functions.html
 *   https://docs.aws.amazon.com/athena/latest/ug/functions.html
 */

export const REGULAR_FUNCTIONS = [
  // Arithmetic / math
  'abs',
  'ceil',
  'ceiling',
  'cos',
  'exp',
  'floor',
  'greatest',
  'least',
  'ln',
  'log',
  'log10',
  'log2',
  'mod',
  'pow',
  'power',
  'rand',
  'random',
  'round',
  'sign',
  'sin',
  'sqrt',
  'tan',
  'truncate',

  // Cast / type conversion
  'cast',
  'try',
  'try_cast',
  'typeof',

  // String
  'char_length',
  'character_length',
  'chr',
  'codepoint',
  'concat',
  'format',
  'from_base',
  'from_hex',
  'from_utf8',
  'length',
  'lower',
  'lpad',
  'ltrim',
  'position',
  'replace',
  'reverse',
  'rpad',
  'rtrim',
  'split',
  'split_part',
  'split_to_map',
  'strpos',
  'substr',
  'substring',
  'to_base',
  'to_hex',
  'to_utf8',
  'trim',
  'upper',

  // Regex
  'regexp_extract',
  'regexp_extract_all',
  'regexp_like',
  'regexp_replace',
  'regexp_split',

  // Date / time
  'current_date',
  'current_time',
  'current_timestamp',
  'date',
  'date_add',
  'date_diff',
  'date_format',
  'date_parse',
  'date_trunc',
  'day',
  'day_of_month',
  'day_of_week',
  'day_of_year',
  'extract',
  'format_datetime',
  'from_iso8601_date',
  'from_iso8601_timestamp',
  'from_unixtime',
  'hour',
  'localtime',
  'localtimestamp',
  'minute',
  'month',
  'now',
  'parse_datetime',
  'second',
  'to_iso8601',
  'to_unixtime',
  'week',
  'year',

  // Conditional
  'coalesce',
  'if',
  'nullif',

  // JSON
  'is_json_scalar',
  'json_array_contains',
  'json_array_length',
  'json_extract',
  'json_extract_scalar',
  'json_format',
  'json_parse',
  'json_size',

  // Array
  'array_agg',
  'array_distinct',
  'array_except',
  'array_intersect',
  'array_join',
  'array_max',
  'array_min',
  'array_position',
  'array_remove',
  'array_sort',
  'array_union',
  'cardinality',
  'concat',
  'contains',
  'element_at',
  'filter',
  'flatten',
  'reduce',
  'sequence',
  'shuffle',
  'slice',
  'transform',
  'zip',
  'zip_with',

  // Map
  'element_at',
  'map',
  'map_concat',
  'map_entries',
  'map_filter',
  'map_from_entries',
  'map_keys',
  'map_values',
  'multimap_agg',

  // Hash
  'md5',
  'sha1',
  'sha256',
  'xxhash64',

  // URL
  'url_decode',
  'url_encode',
  'url_extract_fragment',
  'url_extract_host',
  'url_extract_parameter',
  'url_extract_path',
  'url_extract_port',
  'url_extract_protocol',
  'url_extract_query',
];

export const AGGREGATE_FUNCTIONS = [
  // Standard SQL aggregates supported by Trino/Athena.
  'any_value',
  'approx_distinct',
  'approx_percentile',
  'approx_set',
  'array_agg',
  'avg',
  'bitwise_and_agg',
  'bitwise_or_agg',
  'bool_and',
  'bool_or',
  'checksum',
  'corr',
  'count',
  'count_if',
  'covar_pop',
  'covar_samp',
  'every',
  'geometric_mean',
  'histogram',
  'kurtosis',
  'map_agg',
  'map_union',
  'max',
  'max_by',
  'merge',
  'min',
  'min_by',
  'multimap_agg',
  'numeric_histogram',
  'regr_intercept',
  'regr_slope',
  'skewness',
  'stddev',
  'stddev_pop',
  'stddev_samp',
  'sum',
  'var_pop',
  'var_samp',
  'variance',
];

export const ALL_KEYWORDS = [
  'SELECT',
  'FROM',
  'WHERE',
  'GROUP',
  'HAVING',
  'ORDER',
  'BY',
  'LIMIT',
  'OFFSET',
  'WITH',
  'ASC',
  'AS',
  'AND',
  'OR',
  'DESC',
  'NULL',
  'NOT',
  'INTERSECT',
  'INTO',
  'IN',
  'DISTINCT',
  'JOIN',
  'INNER',
  'LEFT',
  'RIGHT',
  'FULL',
  'CROSS',
  'OUTER',
  'ON',
  'USING',
  'UNION',
  'ALL',
  'ILIKE',
  'LIKE',
  'BETWEEN',
  'EXCEPT',
  'WINDOW',
  'OVER',
  'PARTITION',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
  'IS',
  'TRUE',
  'FALSE',
];

/** Keywords useful for WHERE or ORDER BY clauses */
export const KEYWORDS_FOR_WHERE_OR_ORDER_BY = [
  'AND',
  'OR',
  'NOT',
  'IN',
  'LIKE',
  'ILIKE',
  'BETWEEN',
  'IS',
  'NULL',
  'TRUE',
  'FALSE',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
  'ASC',
  'DESC',
];
