name: hdx-ci
services:
  otel-collector:
    build:
      context: .
      dockerfile: docker/otel-collector/Dockerfile
      target: dev
    environment:
      CLICKHOUSE_ENDPOINT: 'tcp://ch-server:9000?dial_timeout=10s'
      HYPERDX_OTEL_EXPORTER_CLICKHOUSE_DATABASE: ${HYPERDX_OTEL_EXPORTER_CLICKHOUSE_DATABASE}
      HYPERDX_OTEL_EXPORTER_TABLES_TTL: '87600h'
      HYPERDX_API_KEY: ${HYPERDX_API_KEY}
      HYPERDX_LOG_LEVEL: ${HYPERDX_LOG_LEVEL}
    volumes:
      - ./docker/otel-collector/config.yaml:/etc/otelcol-contrib/config.yaml
    restart: on-failure
    networks:
      - internal
    depends_on:
      - ch-server
  ch-server:
    image: clickhouse/clickhouse-server:26.1-alpine
    environment:
      # default settings
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ./docker/clickhouse/local/config.xml:/etc/clickhouse-server/config.xml
      - ./docker/clickhouse/local/users.xml:/etc/clickhouse-server/users.xml
    restart: on-failure
    ports:
      - '${HDX_CI_CH_PORT:-18123}:8123' # http api
    networks:
      - internal
  db:
    image: mongo:5.0.32-focal
    command: --port 29999
    ports:
      - '${HDX_CI_MONGO_PORT:-39999}:29999'
    networks:
      - internal
networks:
  internal:
