export const semanticColorsGrouped = {
  backgrounds: [
    'color-bg-body',
    'color-bg-surface',
    'color-bg-muted',
    'color-bg-highlighted',
    'color-bg-sidebar',
    'color-bg-header',
    'color-bg-hover',
    'color-bg-active',
    'color-bg-field',
    'color-bg-field-highlighted',
    'color-bg-neutral',
    'color-bg-success',
    'color-bg-danger',
    'color-bg-warning',
    'color-bg-brand',
    'color-bg-modal',
    'color-bg-code',
    'color-bg-kbd',
  ],
  borders: ['color-border', 'color-border-code', 'color-border-muted'],
  text: [
    'color-text',
    'color-text-inverted',
    'color-text-primary',
    'color-text-primary-hover',
    'color-text-secondary',
    'color-text-muted',
    'color-text-muted-hover',
    'color-text-success',
    'color-text-success-hover',
    'color-text-danger',
  ],
  icons: ['color-icon-primary', 'color-icon-muted'],
  overlay: ['color-overlay', 'color-backdrop'],
  states: ['color-state-hover', 'color-state-selected', 'color-state-focus'],
  json: [
    'color-json-string',
    'color-json-number',
    'color-json-boolean',
    'color-json-key',
    'color-json-object',
    'color-json-array',
    'color-json-punctuation',
  ],
};
