export const semanticColorsGrouped = {
  backgrounds: [
    'color-bg-body',
    'color-bg-surface',
    'color-bg-muted',
    'color-bg-highlighted',
    'color-bg-sidebar',
    'color-bg-header',
    'color-bg-hover',
    'color-bg-active',
    'color-bg-field',
    'color-bg-field-highlighted',
    'color-bg-field-addon',
    'color-bg-neutral',
    'color-bg-success',
    'color-bg-danger',
    'color-bg-warning',
    'color-bg-modal',
    'color-bg-code',
    'color-bg-kbd',
  ],
  borders: ['color-border', 'color-border-code', 'color-border-muted'],
  text: [
    'color-text',
    'color-text-inverted',
    'color-text-primary',
    'color-text-primary-hover',
    'color-text-secondary',
    'color-text-muted',
    'color-text-muted-hover',
    'color-text-success',
    'color-text-success-hover',
    'color-text-brand',
    'color-text-brand-hover',
    'color-text-danger',
  ],
  icons: ['color-icon-primary', 'color-icon-muted'],
  overlay: ['color-overlay', 'color-backdrop'],
  states: [
    'color-state-hover',
    'color-state-selected',
    'color-state-focus',
    'color-outline-focus',
  ],
  json: [
    'color-json-string',
    'color-json-number',
    'color-json-boolean',
    'color-json-key',
    'color-json-object',
    'color-json-array',
    'color-json-punctuation',
  ],
  charts: [
    'color-chart-1',
    'color-chart-2',
    'color-chart-3',
    'color-chart-4',
    'color-chart-5',
    'color-chart-6',
    'color-chart-7',
    'color-chart-8',
    'color-chart-9',
    'color-chart-10',
    'color-chart-success',
    'color-chart-warning',
    'color-chart-error',
    'color-chart-error-highlight',
    'color-chart-warning-highlight',
  ],
};
