import {
  AlertSource,
  type IacImportManifest,
} from '@hyperdx/common-utils/dist/types';

//
// Single source of truth for everything HyperDX asserts about the ClickHouse
// Terraform provider (github.com/ClickHouse/terraform-provider-clickhouse).
// When the provider changes, this file and its tests are the only places to
// update.

const TERRAFORM_PROVIDER_SOURCE = 'ClickHouse/clickhouse';
// First provider version shipping the ClickStack (HyperDX) resources.
const TERRAFORM_PROVIDER_VERSION_CONSTRAINT = '>= 3.22.0';

export type IacResourceType =
  | 'dashboard'
  | 'alert'
  | 'saved_search'
  | 'source'
  | 'connection'
  | 'webhook';

const TERRAFORM_RESOURCE_TYPES: Record<IacResourceType, string> = {
  dashboard: 'clickhouse_clickstack_dashboard',
  alert: 'clickhouse_clickstack_alert',
  saved_search: 'clickhouse_clickstack_saved_search',
  source: 'clickhouse_clickstack_source',
  connection: 'clickhouse_clickstack_connection',
  webhook: 'clickhouse_clickstack_webhook',
};

export type IacResourceRef = {
  type: IacResourceType;
  id: string;
  name?: string;
};

// The manifest contract lives in common-utils so this module and the router
// that serves it (packages/api/src/routers/api/iac.ts) cannot drift.
export type { IacImportManifest };

// `name` is optional throughout: it is a plain (non-required) String on the
// Connection/Source/SavedSearch schemas, so the manifest can legitimately
// carry an entry without one. `terraformResourceLabel` falls back to the type.
export type IacConnectionRef = IacImportManifest['connections'][number];

/**
 * The provider models only saved-search alerts — a tile alert has no
 * corresponding resource, so offering one for import produces a command that
 * fails. Shared by the bulk export and the per-alert popover so the two cannot
 * disagree about what is eligible.
 */
export function isImportableAlert(alert: {
  source?: string;
  savedSearchId?: string;
}): boolean {
  // `source` is authoritative whenever it is set. The savedSearchId fallback
  // covers only legacy rows that predate the discriminator — it must NOT be an
  // unconditional `||`, because converting a saved-search alert to a tile alert
  // leaves the old savedSearch reference behind: `makeAlert` passes
  // `savedSearch: undefined` and Mongoose 6 deletes undefined keys from the
  // `$set` instead of clearing the field. A tile alert can therefore still
  // report a savedSearchId, and the provider cannot model it.
  return (
    alert.source === AlertSource.SAVED_SEARCH ||
    (alert.source == null && !!alert.savedSearchId)
  );
}

export function terraformResourceLabel({
  type,
  id,
  name,
}: IacResourceRef): string {
  const slug = (name ?? '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 48);
  const base =
    slug && /^[a-z]/.test(slug) ? slug : `${type}_${slug}`.replace(/_+$/, '');
  // Short id suffix keeps labels unique when two resources share a name.
  return `${base}_${id.slice(-5)}`;
}

export function buildImportBlock(ref: IacResourceRef): string {
  return `import {
  to = ${TERRAFORM_RESOURCE_TYPES[ref.type]}.${terraformResourceLabel(ref)}
  id = "${ref.id}"
}`;
}

export function buildProviderBlock(endpoint: string): string {
  return `terraform {
  required_providers {
    clickhouse = {
      source  = "${TERRAFORM_PROVIDER_SOURCE}"
      version = "${TERRAFORM_PROVIDER_VERSION_CONSTRAINT}"
    }
  }
}

provider "clickhouse" {
  clickstack_endpoint = "${endpoint}"
  # Set the CLICKSTACK_API_KEY environment variable to your Personal API
  # Access Key (Team Settings -> API & Agents). Avoid committing keys.
}`;
}

// Connections whose provenance is unknown, or which the server marks as
// platform-provisioned, are exposed as reference-only locals: on ClickHouse
// Cloud the provider cannot manage them. Only a connection the server marks
// explicitly self-managed becomes an import block instead.
function buildConnectionLocalsBlock(connections: IacConnectionRef[]): string {
  const lines = connections.map(
    c =>
      `  ${terraformResourceLabel({ type: 'connection', id: c.id, name: c.name })}_id = "${c.id}"`,
  );
  return `# These connections are either platform-provisioned or of unrecorded
# provenance, so Terraform cannot manage them. Reference them by id instead.
locals {
${lines.join('\n')}
}`;
}

export function buildImportFile({
  endpoint,
  resources,
  connectionLocals = [],
}: {
  endpoint: string;
  resources: IacResourceRef[];
  connectionLocals?: IacConnectionRef[];
}): string {
  const sections = [
    buildProviderBlock(endpoint),
    ...(connectionLocals.length
      ? [buildConnectionLocalsBlock(connectionLocals)]
      : []),
    ...resources.map(buildImportBlock),
  ];
  return `# HyperDX Terraform import file
# Generated by HyperDX. Review before committing to your repository.
#
# 1. Place this file in your Terraform project.
#    If your project already declares the ClickHouse provider, delete the
#    "terraform" and "provider" blocks below — Terraform allows only one of
#    each per module.
# 2. export CLICKSTACK_API_KEY=<your Personal API Access Key>
# 3. terraform init          # installs the ClickHouse provider declared above
# 4. terraform plan -generate-config-out=generated.tf
# 5. Review generated.tf carefully, then: terraform apply
#
# Before you apply:
#
# * Review generated.tf against the real resource. The provider's ClickStack
#   resources are alpha and do not model every HyperDX feature — PromQL tiles
#   in particular have no representation. A dashboard's configuration is
#   written back whole, so applying a config that omits something deletes it.
# * Resource addresses below are derived from each resource's current name.
#   Renaming a resource in HyperDX and re-exporting produces a different
#   address, which Terraform reads as destroy-and-recreate. Add a "moved"
#   block, or edit the address back, if you rename something later.
# * ClickStack resources in the provider are in alpha; behaviour may change
#   between provider versions.

${sections.join('\n\n')}
`;
}

export function collectImportableResources(
  manifest: IacImportManifest,
  selectedTypes: IacResourceType[],
): {
  resources: IacResourceRef[];
  connectionLocals: IacConnectionRef[];
  skippedTileAlerts: number;
} {
  const resources: IacResourceRef[] = [];
  let skippedTileAlerts = 0;

  // Dispatched explicitly rather than looping a {type, key} table. The table
  // form could not tie a resource type to its manifest key, so a mispaired
  // entry compiled fine and needed an `as` cast to read alert-only fields —
  // between them that silently dropped resources and miscounted skips.
  const add = (
    type: IacResourceType,
    items: { id: string; name?: string }[],
  ) => {
    if (!selectedTypes.includes(type)) return;
    for (const item of items) {
      resources.push({ type, id: item.id, name: item.name });
    }
  };

  add('source', manifest.sources);
  add('saved_search', manifest.savedSearches);
  add('webhook', manifest.webhooks);

  if (selectedTypes.includes('alert')) {
    for (const alert of manifest.alerts) {
      if (!isImportableAlert(alert)) {
        skippedTileAlerts += 1;
        continue;
      }
      resources.push({ type: 'alert', id: alert.id, name: alert.name });
    }
  }

  add('dashboard', manifest.dashboards);

  // A connection is only safe to import when the server affirmatively says it
  // is self-managed. Platform-provisioned connections (ClickHouse Cloud) can't
  // be managed by the provider, and `undefined` means nobody has recorded the
  // provenance — so both fall back to reference-only locals.
  //
  // The safe floor is deliberate. No client-side signal distinguishes Cloud
  // from self-hosted: IS_CLICKHOUSE_BUILD marks the bundled ClickStack
  // distribution (itself self-hosted), and an origin/domain check breaks on
  // custom domains and misreads the public `*.clickhouse.com` demo servers.
  // Only the server knows, via Connection.platformProvisioned.
  //
  // Nothing populates that field yet, so today every connection takes the
  // locals path — the same behaviour as before it existed.
  const connectionsSelected = selectedTypes.includes('connection');
  const connectionLocals: IacConnectionRef[] = [];
  if (connectionsSelected) {
    for (const c of manifest.connections) {
      if (c.platformProvisioned === false) {
        resources.push({ type: 'connection', id: c.id, name: c.name });
      } else {
        connectionLocals.push(c);
      }
    }
  }

  return { resources, connectionLocals, skippedTileAlerts };
}
