name: Post-deployment Tests
on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'

jobs:
  post-deployment-tests:
    runs-on: ubuntu-latest

    # Only run for successful deployments
    if: github.event_name == 'repository_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Deployment URL
        run: |
          DEPLOYMENT_URL="${{ github.event.client_payload.url }}"
          if [[ ! "$DEPLOYMENT_URL" =~ ^https://.*\.vercel\.app/?$ ]]; then
            echo "❌ Invalid deployment URL: $DEPLOYMENT_URL"
            exit 1
          fi
          echo "✅ Valid deployment URL: $DEPLOYMENT_URL"

      - name: Wait for deployment to be ready
        run: |
          DEPLOYMENT_URL="${{ github.event.client_payload.url }}"
          echo "🕐 Waiting for deployment to be ready: $DEPLOYMENT_URL"

          for i in {1..30}; do
            if curl -s --fail "$DEPLOYMENT_URL" > /dev/null; then
              echo "✅ Deployment is ready!"
              break
            fi
            
            if [ $i -eq 30 ]; then
              echo "❌ Deployment not ready after 5 minutes"
              exit 1
            fi
            
            echo "⏳ Attempt $i/30 - waiting 10 seconds..."
            sleep 10
          done

      - name: Stably Runner Action
        uses: stablyhq/stably-runner-action@v3
        with:
          test-suite-id: cmc548u5u0001la04q7y8ddj2
          github-token: ${{ secrets.GITHUB_TOKEN }}
          api-key: ${{ secrets.STABLY_API_KEY }}
          environment: PRODUCTION
          variable-overrides: |
            {
              "SITE_URL": "${{ github.event.client_payload.url }}"
            }

      - name: Test Summary
        if: always()
        run: |
          echo "📊 Test Summary"
          echo "Deployment URL: ${{ github.event.client_payload.url }}"
          echo "Environment: ${{ github.event.client_payload.environment }}"
          echo "Event: ${{ github.event.action }}"
          echo "Status: ${{ job.status }}"
