name: Push Downstream V2
on:
  push:
    branches: [v2]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  push-downstream:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/github-script@v7
        env:
          ACTOR: ${{ github.actor }}
          MESSAGE: ${{ github.event.head_commit.message }}
          SHA: ${{ github.sha }}
        with:
          github-token: ${{ secrets.DOWNSTREAM_TOKEN }}
          script: |
            const { ACTOR, MESSAGE, SHA } = process.env;
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: '${{ secrets.DOWNSTREAM_OWNER }}',
              repo: '${{ secrets.DOWNSTREAM_REPO_V2 }}',
              workflow_id: '${{ secrets.DOWNSTREAM_WORKFLOW_ID_V2 }}',
              ref: 'main',
              inputs: {
                sha: SHA,
                actor: ACTOR,
                message: MESSAGE
              }
            });
